### ISSUE TITLE
Arg

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#181]
Sorry for stupid question, but 
![image](https://cloud.githubusercontent.com/assets/9086983/11764219/2444f61a-a130-11e5-95e7-aaeb2418f8ee.png)
argument users i cant get in logger.debug(users); it sending undefined, can u help me, why?

**Comment by RJacksonm1** [comment]
I can imagine that code returning an empty array (`[]`) for users, because Javascript is an asynchronous language - your `logger.debug(users);` line is likely going to be executed before your `users[i] = rows[0].user_steamid;` line.  As far as I can see `users` should not be undefined.

Regardless, this is not a node-dota2 issue. This issues section is not the place to go for help writing and debugging your applications, unless your issue directly relates to node-dota2 usage.

**Comment by oleghalin** [comment]
Yes, it isnt node-dota issue, but i cant understand how to write users and after use this arg in code?
