### ISSUE TITLE
Bot user to enter game as broadcaster

### ISSUE THREAD

**Issue by Altantur** [RJacksonm1/node-dota2#194]
Hi, I've been enjoying what you guys building. But I have question about Bot user.
Can bot enter the game as spectator and start game by function? So Bot observes the game and inform at least won team. Please anyone have suggestion?

**Comment by Crazy-Duck** [comment]
we currently have functionality allowing a bot to create a lobby, join a team (including broadcaster), invite people to it and start it, after which the bot will continuously receive updates on its state. As far as I know we don't have the possibility yet to spectate a specific (ongoing) game (functionality to accept lobby invites for example is still missing). However, the codebase is completely open source and easily extendable so feel free to add any functionality. We always welcome new contributions

**Comment by jimmydorry** [comment]
The dev branch is currently the most up to date and feature complete version. So make sure to start there.

https://github.com/RJacksonm1/node-dota2/tree/dev

**Comment by jimmydorry** [comment]
Stale issue. Re-open or make a new issue.

- Please rate the service provided on a scale of 1 to 7
- Please rate your satisfaction as a result of interaction with agent [#82414 - @Crazy-Duck ] on a scale of 1 to 6.5

Have a nice day, and remember that Dota2 is serious business. Your happiness matters to someone.

**Comment by RJacksonm1** [comment]
wot

**Comment by KoofKoof** [comment]
I am seeking answer for this question as well.  Official Dota 2 API doesn't allow developers to obtain information from private lobby matches. In order to find out who won the match,I need to create a steam bot using node-dota2 and listen match events.From the comments, I understood that this feature isn't implemented yet. Are there any plans for implementing this feature or should I start implementing this myself? Please don't answer this question with "wot" :)

**Comment by jimmydorry** [comment]
Have a look through the readme. Just starting the game as a broadcaster will leave you in the lobby. You get a lobby summary and even game events, I believe.

Definitely possible, and others have done it.

Try listening to practiceLobbyUpdate responses, and if that fails... nethook it (like wireShark) to see what is happening.

**Comment by KoofKoof** [comment]
Thanks for the answer. I have already read the readme and I knew practiceLobbyUpdate but I thought it it is used to retrieve lobby data( e.g. "lobby created","user joined") and it wouldn't return ingame data. I will definitely try listening it and look for useful data when I get home from work.

Also can you please elaborate your  answer: "Definitely possible, and others have done it."
Who have done it? I couldn't find any information regards to this. Thanks in advance.

**Comment by jimmydorry** [comment]
There won't be much about it. I can point you at a more specifically targeted but less general purpose library in C++. You could then compare functionality with this library to see what they are doing.

I know it works, because it literally powers the biggest semi-official dota2 league.

https://github.com/paralin/Dota2
https://github.com/paralin/Dota2LobbyDump
http://hastebin.com/enopuliric.json

His example of JSON response is probably the practiceLobbyUpdate response... so I would just go ahead and play with our node library.

**Comment by KoofKoof** [comment]
Thanks you so much for your detailed answers.

**Comment by jimmydorry** [comment]
NP. If it were me, I would check that event and see if it looks like the haste in dump. If yes, then your job is easy.

**Comment by KoofKoof** [comment]
Yeah,practiceLobbyUpdate event looks promising. Also can you give me the name of the semi-official dota2 league, so I can better understand the workflow?

**Comment by jimmydorry** [comment]
FaceIT. They do TI open qualifiers, and run other qualifiers for official events. They also do their own public league.

**Comment by nishadtardalkar** [comment]
Can someone verify that a bot is still able to connect as a broadcaster?
Coz mine just fails to load in the game during DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD
