### ISSUE TITLE
Incorrect type of match_id

### ISSUE THREAD

**Issue by andreibotezatu** [RJacksonm1/node-dota2#239]
Hi,

I found one bug in this line: 
https://github.com/RJacksonm1/node-dota2/blob/bd4eedf57075ab9d65091b77cc2b12da2cd7125d/proto/dota_gcmessages_client.proto#L2239

this seems that the match_id field need to be as uint32 not as uint64, because with 64 it's gets invalid match_id and a error from protobuff when decoding.

Thanks!

**Comment by Crazy-Duck** [comment]
well, that would be annoying actually, cause that's part of the game's code... besides matchid's will VERY soon (if they haven't already) surpass a 32bit integer, so a uint32 physically can't hold them anymore. That's why Valve is fixing their entire backend to switch to 64bit. Are you sure you're running the latest version of the library and that you updated all dependencies?

**Comment by jimmydorry** [comment]
Try downloading this library from github and dropping it where your local copy is. It's possible that the version in npm is out of date too. If anything, it's likely there are a few uint32 gotchas left in this library that need to be updated to handle uint64. I'm not aware of any yet, though.

**Comment by imayhaveborkedit** [comment]
Also see: http://dev.dota2.com/showthread.php?t=190337

**Comment by jimmydorry** [comment]
No further info given.
