### ISSUE TITLE
requestPlayerInfo has stopped working after the battle pass update

### ISSUE THREAD

**Issue by c00kie17** [RJacksonm1/node-dota2#269]
Hi I wanted to update that requestPlayerInfo has stopped working and is not returning anything after the new battle pass update that valve added 2 days ago.

**Comment by jimmydorry** [comment]
It may be as simple as just updating the protobufs. Will take a quick look tomorrow.

**Comment by Crazy-Duck** [comment]
I did it a pull for the new proto's but it seems a lot of stuff got swapped around. The protobuf got changed (so much for the spirit of retrocompatibility), it now takes an array of objects instead of an array of ids. Gonna have to tinker around a bit and check if it's sufficient to just wrap the ids, if not we're gonna need a 4.0.0 push

**Comment by Crazy-Duck** [comment]
Hotfixed in latest pull on the dev branch
I might create a new function getPlayerinfos which implements the entire spec later on. I didn't do any further checking, so it's very much a possibility that other stuff will pop up later on. Just create an issue and I'll look into fixing it

**Comment by c00kie17** [comment]
Hi what do you mean it takes an array of objects? Objects of what? If anything else pops up I will update it here.

**Comment by Crazy-Duck** [comment]
It's a backend change on Valve's end. The protobuf used to look like this:
```
{
    account_ids: [id1, id2, ...]
}
```
whereas now it's become
```
{
    profile_infos: [
        {
            account_id: id1,
            timestamp: ts1
        },
        {
            account_id: id1,
            timestamp: ts1
        },
        ...
    ]
}
```
However this is of no consequence to you since you use the `requestPlayerInfo` function we provide, which usage hasn't changed. We'll be pushing the fix to the main repo soonish, in the mean time you can use the dev branch if you want things to work again.

**Comment by c00kie17** [comment]
Oh okay, thanks! Ill be using the dev branch. Thanks a lot for the quick response.

**Comment by jimmydorry** [comment]
He's a super star

**Comment by c00kie17** [comment]
Hi i know i should probably start a new thread for this but, I was wondering if you all were working on a way to get live game stats for all games ? Or if its even possible to right now?

**Comment by jimmydorry** [comment]
Look at the open issues, it gets raised almost every day.

**Comment by jimmydorry** [comment]
Original issue should be resolved now. New version will be in npm soon
