### ISSUE TITLE
sometimes request just hangs the program and never returns

### ISSUE THREAD

**Issue by SmaugTheGreat** [RJacksonm1/node-dota2#280]
So I have the code like below. It should theoretically just request a profile card and then when it got the result it should request the next one. However, after a random amount of requests (usually 10) it just hangs. The last debug message I get is `9 Jun 20:39:48 - Sending profile card request
`. I don't know if it is due to steam connection problems, but there doesn't seem to be any method for setting a timeout?

            steamClient.on('logOnResponse', () => {
                console.log("Connected!");
                Dota2.on('error', (err) => {
                    console.error("Error:", err);
                });

                Dota2.once('ready', () => {
                    let index = 0;
                    let getCard = () => {
                        if(index >= result.length) { // result = array players to scan
                            console.log("End");
                            return;
                        }
                        console.log("Getting card for " + index);
                        Dota2.requestProfileCard(86717663, (err, response) => { // using the same constant id for test purposes
                            if(err) console.log("Error: " + err);
                            console.log(index+": Found data!");
                            index++;
                            getCard();
                        })
                    };

                    getCard();
                });

                Dota2.launch();
            });

            steamClient.on('error', (err) => {
                console.error("Error:", err);
            });

            steamClient.connect();

**Comment by jimmydorry** [comment]
There are going to be rate limits, and the GC can be quite unstable. That kind of logic sounds better implemented in the bot than the library... but I defer to @Crazy-Duck on this one.

**Comment by SmaugTheGreat** [comment]
But this is a problem. I would love to just build the timeout logic myself, but it will cause it to leak memory as I send the callback (and all its captured variables) with the request and have no way to remove it from memory.

**Comment by Crazy-Duck** [comment]
Yeah, you're probably running into rate limiting issues, the GC doesn't really like people slamming it with too many requests in a short time-frame. That's why Valve changed the client itself so you need to actually rightclick player images now before the profile card loads. This rate-limiting behaviour should be built into the bot itself as @jimmydorry is saying, we can hardly impose arbitrary limits ourself. I might look into adding configurable ratelimiting behaviour into my bot framework when I'm able to free up some time. In any case, rate limiting shouldn't cause memory leaks. You simply should send your requests spread out in time so they all actually return, instead of just slamming the GC and letting the requests time out if they don't return. That's the kind of behaviour that gets your account banned.

**Comment by jimmydorry** [comment]
Well answered! Keep an eye on https://github.com/Crazy-Duck/node-dota2-bot @SmaugTheGreat

**Comment by SmaugTheGreat** [comment]
@Crazy-Duck I tried to space out the requests so that there's 30 seconds between them but the problem remains. My timeout logic is memory-leaking because it stores a closure+callback together with the request which then is hold in memory for infinite duration or until I disconnect the client.
