### ISSUE TITLE
Ability to pass a proxy to requestMatchDetails

### ISSUE THREAD

**Issue by Saicheg** [RJacksonm1/node-dota2#295]
Hey!

Regarding documentation:

```
requestMatchDetails() - There is a server-side rate-limit of 100 requests per 24 hours on this method.
```

So i am thinking if it's doeble/realistic to add proxy-server option for this method call, or somewhere else?

**Comment by jimmydorry** [comment]
That doesn't sound like something that should be part of the library. You should look at making logic within your bot to handle this. I should warn you though, that there are various IP restrictions set too, so you won't simply be able to run dozens of bots on the same IP.

**Comment by Saicheg** [comment]
@jimmydorry great. If you can tell me some restrictions you faced with - it would be really helpful ?

**Comment by Crazy-Duck** [comment]
Be careful as well, this is an issue which has popped up in the past on the node-steam pages as well. See [here](https://github.com/seishun/node-steam/issues/140) for more information. Basically using proxies is against the Stea Subscriber Agreement, so you shouldn't be using one. Since node-dota2 does not do any networking, and relies on node-steam for that, we basically just follow their policy

**Comment by Crazy-Duck** [comment]
Basically, if you're planning on trying to circumvent the rate-limiting on the methods by using proxies, you'll probably get your account banned. The 'proper' way to do things is having multiple accounts running from multiple IP's.

**Comment by jimmydorry** [comment]
You will know when you are rate limited. Just design with scaling kept in mind. It violates the spirit of it all if it was easy to know where the limits sit.

**Comment by Saicheg** [comment]
@Crazy-Duck @jimmydorry thank you guys both for answers and for great library. Closing this issue.
