### ISSUE TITLE
[discussion] User management with node-dota2

### ISSUE THREAD

**Issue by rafaelcastrocouto** [RJacksonm1/node-dota2#306]
Hi Jack,
Gratz, your code is awesome!
I'm considering the possibility of making all user login and chat features for my game with node-dota2. The game has a nodejs server on heroku and is already available to play at [dotacard.ga](http://dotacard.ga) and the repository is also on [github](http://github.com/rafaelcastrocouto/dotacard).
Before I jump into your code, I thought it would be smart to ask you if all this is possible ... and if it is possible, would Valve be ok with it? Or is there a more recommended way to do it? 
Thx a lot

**Comment by Crazy-Duck** [comment]
First and foremost, our lord and saviour is called Sir Robert Jackson. Now that that's out of the way, it seems to me you're trying to hammer a nail using a screwdriver. If I understand correctly, you're looking notably for an easy login protection for your personal game, so you can recognize players when they come back. This library will not help you with that. Node-dota2 is a wrapper around the node-steam node js library. Basically we reverse engineer the reborn client's communication with the game coordinator, based on the reverse engineering of steam itself (which is easy, since both use the same protocol, i.e. protobuf, to communicate with Valve servers). 
Since your game, on first sight, correct me if I'm wrong, has nothing to do with dota, other than its theme, you'll find little solace in the functionalities we offer. Yes using our login you could probably put something in place which might resemble on first sight what you're aiming for, it would still be the wrong tool for the job (just like you can hammer a nail with a screwdriver, it just won't work as well as when you're using a hammer). For one it would impede anyone logged in to your game to play dota in the mean time, since the GC would detect they're already logged in.

Now that I've (hopefully) thoroughly bashed your hopes of using this library, let me at least point you in the direction of a hammer :) The solution you're looking for, and which is pretty easy to implement, is OAuth 2.0. You want your users to authentify themselves with their steam account, which is something that Valve supports and offers. Many third party websites use this mechanism to authenticate users since it's so easy: Valve handles all the login and account management and they tell you who you're dealing with. If you want an example of how this is implemented, head over to the [yasp github repo](https://github.com/yasp-dota/yasp). Yasp has always used steam login, so if you want to see it in action, visit their site @ http://yasp.co

**Comment by rafaelcastrocouto** [comment]
Thank you sooo much Crazy-Duck,
Your answer spared me a lot of useless reading (and most probably coding).
Sorry about your saviour ... all hail Lord Robert Jackson! 
Thx again

**Comment by jimmydorry** [comment]
Or more specifically, you may be looking for Valve's OpenID. http://steamcommunity.com/dev

You can read about openID anywhere, as it is a standard. Plugin the valve openID url, and away you go!

**Comment by rafaelcastrocouto** [comment]
Thx a lot jimmy, I already got my Steam Web API Key!
Although I don't use express and I usually try do go deep in every detail of what I'm coding (trying hard not to reinvent the wheel) ... after reading a little, I still think I'm going to use passport-steam.
Basically cuz I can use passportjs to easily implement some other login strategies like google and facebook ... and I also cuz want to solve this as fast as possible... I'm coding this game alone and it's really a lot of work.
